### ISSUE TITLE
Fix travis ci badge

### ISSUE THREAD

**Issue by BenBarnard** [gabrielodom/mvMonitoring#26]
Since your repository is now public you do not need to use travis-ci.com anymore. Travis-ci.org shouldn't give the obscure error you were getting before. It might also be nice to put a cran badge up since you are on cran now. I am assigning this to @gabrielodom since he is the owner of the repository and as such is the only one that can setup travis for this repository. If and when ownership changes the travis setup will probably break and the new owner will have to fix.

**Comment by gabrielodom** [comment]
Added CRAN tag. I'm leaving the Travis-CI tag with a note that it corresponds to the devel version.
